### ISSUE TITLE
Preliminary Problem Statement

### ISSUE THREAD

**Issue by bibikar** [energy-plus-senior-design/issues#1]
Instructions: https://drive.google.com/file/d/1EtKjI8lUj0FKQu9d2cBzzFotbxPwqajG/view?usp=sharing

Google Doc: https://drive.google.com/open?id=17RxKCOqnhVrh3XCQAKZNM35lvdCJ-j_Jt3dM2_hT9VE

### Updated Breakdown

- [x] Introduction @srinjoym @forgetagain 
- [ ] Description of the Design Problem
  - [x] Problem Background @vivianmnguyen @rkoripalli 
    - [ ] Building Energy Plus Models
  - [x] Stakeholder Needs Analysis @srinjoym 
  - [ ] Design Functionality
    - [x] Linear Model Plan @srinjoym and @forgetagain 
    - [x] Neural Net Model Plan @bibikar @qkpqkp
  - [x] Relevant Standards @forgetagain 
  - [ ] Use Cases @bibikar 
  - [x] Ethical Considerations @qkpqkp 
  - [ ] Project Deliverables @vivianmnguyen @rkoripalli 
    - [ ] Combining Linear and Neural
- [ ] Requirements Specifications
  - [x] Inputs and Outputs Specifications @vivianmnguyen 
  - [ ] User Interface Specifications @rkoripalli 
  - [x] Operating Environment Specifications @srinjoym 
  - [ ] Performance Specifications (again probably want specs from everyone here)
- [ ] Team Qualifications @energy-plus-senior-design/everyone 
- [ ] Conclusion

**Comment by srinjoym** [comment]
We should start work this week. Do you guys want to just separate out into three sections for now and talk about our goals for this semester and next semester?

Something like:
Intro: @srinjoym @forgetagain 
Building Energy Plus Models: @vivianmnguyen @rkoripalli 
Linear Model Plan: @srinjoym and @forgetagain 
Neural Nets Plan: @bibikar @qkpqkp 
Combining Linear and Neural: @vivianmnguyen @rkoripalli 
Conclusion: @bibikar @qkpqkp

**Comment by srinjoym** [comment]
@energy-plus-senior-design/everyone Just updated the breakdown, I randomly assigned people to sections so if yall wanna do a different part just move your name in the top issue. We need to write 6-10 pages of just content, so it's probably a good idea to get started over the weekend/early next week. We also need to schedule a consultation with the writing TA (we can discuss on Monday)
