### ISSUE TITLE
Contact Dr. Santoso

### ISSUE THREAD

**Issue by srinjoym** [energy-plus-senior-design/issues#5]

**Comment by forgetagain** [comment]
According to Professor Zhu, Dr. Santoso will not be able to help with data acquisition. I found a UT grad course that actually teaches about building energy simulations including EnergyPlus: CE397/ARE371. Here's the syllabus: http://www.caee.utexas.edu/prof/novoselac/Classes/ARE383/SyllabusCE397ARE371_Novoselac_Fall2016.pdf
The instructor is Dr. Novoselac.
