### ISSUE TITLE
Start working on Linear Model

### ISSUE THREAD

**Issue by srinjoym** [energy-plus-senior-design/issues#6]

**Comment by forgetagain** [comment]
Figure which variables are important (no dependence)

**Comment by srinjoym** [comment]
Started some preliminary work on fitting a linear model to the data generated from OpenStudio for our test building in this repository: https://github.com/energy-plus-senior-design/linear-model-notebook

Feel free to fork and play around to explore more strategies, there's much more data pre-processing that needs to be done but this provides some initial insight into what variables are important. Right now it's setting high weights on `System Node Humidity Ratio` to fit the data. This may not be available in the real world so we need to look into which metrics are actually attainable from commercial buildings.
